### ISSUE TITLE
Add ability to register custom scalars

### ISSUE THREAD

**Issue by Tworley96** [autoinvent/magql#22] opened 2020-03-11 15:33 UTC
A user should be able to register a new scalar type with Magql and have it be able to convert that scalar to GraphQL

**Comment by kramsey458** [comment] 2020-03-11 15:37
Related to #16, and #20 (draft implementation)

**Comment by davidism** [comment] 2020-03-11 21:11
Duplicate of #16

**Closed by davidism** 2020-03-11 21:11 UTC
